# Generated by Django 5.2.16 on 2026-07-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_records', '0006_clinicalrecord_general_observations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre breve de la actividad asignada al paciente.', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Instrucciones o detalles que el paciente debe seguir para realizar la asignación.', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('psychologist_comments', models.TextField(blank=True, help_text='Indicaciones u observaciones adicionales visibles para el paciente.', verbose_name='Comentarios del psicólogo')),
                ('patient_response', models.TextField(blank=True, help_text='Contenido escrito por el paciente como respuesta a la asignación.', verbose_name='Respuesta del paciente')),
                ('is_visible', models.BooleanField(default=True, help_text='Indica si la asignación puede mostrarse en el portal del paciente.', verbose_name='Visible para el paciente')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('session_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clinical_records.sessionnote', verbose_name='Nota de sesión')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
