# Generated by Django 5.2.16 on 2026-07-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/attachments/%Y/%m/', verbose_name='Archivo')),
                ('uploaded_by', models.CharField(choices=[('PSYCHOLOGIST', 'Psicólogo'), ('PATIENT', 'Paciente')], max_length=20, verbose_name='Subido por')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assignment', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'ordering': ['-created_at'],
            },
        ),
    ]
