# Generated by Django 5.2.16 on 2026-07-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
