# Generated by Django 5.2.16 on 2026-07-17 20:26
import uuid
from django.db import migrations

def populate_assignment_public_ids(apps, schema_editor):
    """
    Asigna un UUID diferente a cada asignación existente
    que todavía no tenga un identificador público.
    """

    Assignment = apps.get_model(
        "assignments",
        "Assignment",
    )

    assignments = Assignment.objects.filter(
        public_id__isnull=True,
    )

    for assignment in assignments.iterator():
        assignment.public_id = uuid.uuid4()

        assignment.save(
            update_fields=["public_id"],
        )

class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_public_id'),
    ]

    operations = [
        migrations.RunPython(
            populate_assignment_public_ids,
            migrations.RunPython.noop,
        ),
    ]
