# Generated by Django 5.2.16 on 2026-07-17 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_populate_assignment_public_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
