# Generated by Django 5.2.15 on 2026-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='administrative_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('IN_PERSON', 'Presencial'), ('VIRTUAL', 'Virtual')], default='IN_PERSON', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_reason',
            field=models.TextField(blank=True),
        ),
    ]
