# Generated by Django 5.2.16 on 2026-07-16 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_administrative_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
