# Generated by Django 5.2.16 on 2026-07-16 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
