# Generated by Django 5.2.16 on 2026-07-16 21:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_availabilityslot_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
