# Generated by Django 5.2.16 on 2026-07-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_availabilityslot_public_id'),
        ('patients', '0001_initial'),
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='availability_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.availabilityslot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'COMPLETED'])), fields=('availability_slot',), name='unique_non_cancelled_appointment_per_slot'),
        ),
    ]
