# Generated by Django 5.2.16 on 2026-07-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Expediente clínico',
                'verbose_name_plural': 'Expedientes clínicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
