# Generated by Django 5.2.16 on 2026-07-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_administrative_notes_and_more'),
        ('clinical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_summary', models.TextField(help_text='Descripción general de los temas abordados durante la sesión.', verbose_name='Resumen de la sesión')),
                ('observations', models.TextField(blank=True, help_text='Observaciones clínicas relevantes identificadas durante la sesión.', verbose_name='Observaciones')),
                ('interventions', models.TextField(blank=True, help_text='Técnicas, ejercicios o intervenciones aplicadas durante la sesión.', verbose_name='Técnicas o intervenciones')),
                ('homework', models.TextField(blank=True, help_text='Actividades o tareas acordadas con el paciente.', verbose_name='Tareas asignadas')),
                ('next_session_plan', models.TextField(blank=True, help_text='Temas u objetivos que se trabajarán en la próxima sesión.', verbose_name='Plan para la siguiente sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to='appointments.appointment', verbose_name='Cita')),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='clinical_records.clinicalrecord', verbose_name='Expediente clínico')),
            ],
            options={
                'verbose_name': 'Nota de sesión',
                'verbose_name_plural': 'Notas de sesión',
                'ordering': ['-appointment__availability_slot__start_time'],
            },
        ),
    ]
