# Generated by Django 5.2.16 on 2026-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0002_sessionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text='Describe la razón principal por la que el paciente inicia el proceso terapéutico.', verbose_name='Motivo de consulta'),
        ),
    ]
