# Generated by Django 5.2.16 on 2026-07-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0003_clinicalrecord_chief_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='current_medication',
            field=models.TextField(blank=True, help_text='Registra los medicamentos que el paciente utiliza actualmente, incluyendo dosis o frecuencia cuando sea relevante.', verbose_name='Medicación actual'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='family_history',
            field=models.TextField(blank=True, help_text='Registra información relevante sobre la dinámica familiar y antecedentes psicológicos o médicos en la familia.', verbose_name='Antecedentes familiares'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Registra enfermedades, tratamientos, cirugías u otra información médica relevante del paciente.', verbose_name='Antecedentes médicos'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='personal_history',
            field=models.TextField(blank=True, help_text='Registra acontecimientos, experiencias o situaciones personales relevantes para el proceso terapéutico.', verbose_name='Antecedentes personales'),
        ),
    ]
