# Generated by Django 5.2.16 on 2026-07-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0004_clinicalrecord_current_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='initial_assessment',
            field=models.TextField(blank=True, help_text='Registra las observaciones, impresiones clínicas e hipótesis obtenidas durante la evaluación inicial del paciente.', verbose_name='Evaluación inicial'),
        ),
    ]
