# Generated by Django 5.2.16 on 2026-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0005_clinicalrecord_initial_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='general_observations',
            field=models.TextField(blank=True, help_text='Registra información adicional relevante sobre el expediente o el proceso terapéutico del paciente.', verbose_name='Observaciones generales'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='therapeutic_objectives',
            field=models.TextField(blank=True, help_text='Registra los objetivos principales que se esperan trabajar durante el proceso terapéutico.', verbose_name='Objetivos terapéuticos'),
        ),
    ]
