# Generated by Django 5.2.16 on 2026-07-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_availability_slot_and_more'),
        ('clinical_records', '0006_clinicalrecord_general_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionnote',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='session_note', to='appointments.appointment', verbose_name='Cita'),
        ),
    ]
