# Generated by Django 5.2.16 on 2026-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0007_alter_sessionnote_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
