# Generated by Django 5.2.16 on 2026-07-18 22:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0009_populate_sessionnote_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionnote',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
