# Generated by Django 5.2.16 on 2026-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
