# Generated by Django 5.2.16 on 2026-07-18 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_populate_patient_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
