# Generated by Django 5.2.16 on 2026-07-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['account__first_name', 'account__last_name'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Indica si el paciente se encuentra actualmente en atención o seguimiento.', max_length=20, verbose_name='Estado'),
        ),
    ]
