# Generated by Django 5.2.16 on 2026-07-20 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_options_patient_status'),
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('DISCHARGED', 'Dado de alta')], default='ACTIVE', help_text='Indica si el paciente se encuentra actualmente en atención o seguimiento.', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PatientPsychologistRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('DISCHARGED', 'Dado de alta')], default='ACTIVE', max_length=20, verbose_name='Estado de la relación')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psychologist_relationships', to='patients.patient', verbose_name='Paciente')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_relationships', to='psychologists.psychologist', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Relación paciente-psicólogo',
                'verbose_name_plural': 'Relaciones paciente-psicólogo',
                'ordering': ('-started_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('patient', 'psychologist'), name='unique_active_patient_psychologist_relationship')],
            },
        ),
    ]
