# Generated by Django 5.2.16 on 2026-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino'), ('OTHER', 'Otro'), ('PREFER_NOT_TO_SAY', 'Prefiero no indicarlo')], max_length=30, verbose_name='Género'),
        ),
    ]
